<?php
/**
 * @file
 * epd_edited_collection.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function epd_edited_collection_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "ds" && $api == "ds") {
    return array("version" => "1");
  }
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_node_info().
 */
function epd_edited_collection_node_info() {
  $items = array(
    'edited_collection' => array(
      'name' => t('Edited collection'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'edited_collection_chapter' => array(
      'name' => t('Edited collection chapter'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
