<?php
/**
 * @file
 * epd_case_study.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function epd_case_study_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-case-study-anchors_conclusion:menutoken/58120e7d374b6.
  $menu_links['menu-case-study-anchors_conclusion:menutoken/58120e7d374b6'] = array(
    'menu_name' => 'menu-case-study-anchors',
    'link_path' => 'menutoken/58120e7d374b6',
    'router_path' => 'menutoken/%',
    'link_title' => 'Conclusion',
    'options' => array(
      'menu_token_link_path' => '[current-page:url]#conclusion',
      'menu_token_data' => array(),
      'menu_token_options' => array(
        'clear' => 0,
      ),
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-case-study-anchors_conclusion:menutoken/58120e7d374b6',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: menu-case-study-anchors_introduction:http://theimpactinitiative1.dev.dd:8083/admin/structure/menu/item/2465/edit#intro.
  $menu_links['menu-case-study-anchors_introduction:http://theimpactinitiative1.dev.dd:8083/admin/structure/menu/item/2465/edit#intro'] = array(
    'menu_name' => 'menu-case-study-anchors',
    'link_path' => 'http://theimpactinitiative1.dev.dd:8083/admin/structure/menu/item/2465/edit#intro',
    'router_path' => '',
    'link_title' => 'Introduction',
    'options' => array(
      'menu_token_link_path' => '[current-page:url]#intro',
      'menu_token_data' => array(),
      'menu_token_options' => array(
        'clear' => 1,
      ),
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'menu_token_link_uuid' => 'menutoken/58120a05ea7e8',
      'identifier' => 'menu-case-study-anchors_introduction:http://theimpactinitiative1.dev.dd:8083/admin/structure/menu/item/2465/edit#intro',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-case-study-anchors_references:menutoken/58120e9bea79f.
  $menu_links['menu-case-study-anchors_references:menutoken/58120e9bea79f'] = array(
    'menu_name' => 'menu-case-study-anchors',
    'link_path' => 'menutoken/58120e9bea79f',
    'router_path' => 'menutoken/%',
    'link_title' => 'References',
    'options' => array(
      'menu_token_link_path' => '[current-page:url]#references',
      'menu_token_data' => array(),
      'menu_token_options' => array(
        'clear' => 0,
      ),
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-case-study-anchors_references:menutoken/58120e9bea79f',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
  );
  // Exported menu link: menu-case-study-anchors_spotlight:menutoken/5818be42de1fa.
  $menu_links['menu-case-study-anchors_spotlight:menutoken/5818be42de1fa'] = array(
    'menu_name' => 'menu-case-study-anchors',
    'link_path' => 'menutoken/5818be42de1fa',
    'router_path' => 'menutoken/%',
    'link_title' => 'Spotlight',
    'options' => array(
      'menu_token_link_path' => '[current-page:url]#spotlight',
      'menu_token_data' => array(),
      'menu_token_options' => array(
        'clear' => 0,
      ),
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-case-study-anchors_spotlight:menutoken/5818be42de1fa',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
  );
  // Exported menu link: menu-case-study-anchors_top-tips-for-donors:menutoken/58120e4f19989.
  $menu_links['menu-case-study-anchors_top-tips-for-donors:menutoken/58120e4f19989'] = array(
    'menu_name' => 'menu-case-study-anchors',
    'link_path' => 'menutoken/58120e4f19989',
    'router_path' => 'menutoken/%',
    'link_title' => 'Top tips for donors',
    'options' => array(
      'menu_token_link_path' => '[current-page:url]#donors',
      'menu_token_data' => array(),
      'menu_token_options' => array(
        'clear' => 0,
      ),
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-case-study-anchors_top-tips-for-donors:menutoken/58120e4f19989',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-case-study-anchors_top-tips-for-researchers:menutoken/58120e1b42d10.
  $menu_links['menu-case-study-anchors_top-tips-for-researchers:menutoken/58120e1b42d10'] = array(
    'menu_name' => 'menu-case-study-anchors',
    'link_path' => 'menutoken/58120e1b42d10',
    'router_path' => 'menutoken/%',
    'link_title' => 'Top tips for researchers',
    'options' => array(
      'menu_token_link_path' => '[current-page:url]#researchers',
      'menu_token_data' => array(),
      'menu_token_options' => array(
        'clear' => 0,
      ),
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-case-study-anchors_top-tips-for-researchers:menutoken/58120e1b42d10',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Conclusion');
  t('Introduction');
  t('References');
  t('Spotlight');
  t('Top tips for donors');
  t('Top tips for researchers');

  return $menu_links;
}
