<?php
/**
 * @file
 * epd_impact_lab_landing_page.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function epd_impact_lab_landing_page_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_learning_guides'.
  $field_bases['field_learning_guides'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_learning_guides',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_long',
  );

  // Exported field_base: 'field_special_collection'.
  $field_bases['field_special_collection'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_special_collection',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_long',
  );

  return $field_bases;
}
