http://www.{default}/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  cache:
    enabled: true
    headers: ['Accept', 'Accept-Language', 'X-Language-Locale']
    cookies: []
    default_ttl: 300
  ssi:
    enabled: false
  upstream: app:http
http://{default}/:
  type: redirect
  redirects:
    expires: -1s
    paths: {}
  to: http://www.{default}/
