<?php

/**
 * @file
 * Module to add blocks containing map descriptions.
 */

module_load_include('inc', 'epd_copyright_licensing', 'epd_copyright_licensing.block');

/**
 * Implements hook_menu().
 */
function epd_copyright_licensing_menu() {
  $items['admin/config/epd/info'] = array(
    'title' => 'Global Information',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('epd_copyright_licensing_settings_form'),
    'access arguments' => array('administer epd copyright and licensing'),
    'file' => 'epd_copyright_licensing.admin.inc',
  );

  return $items;
}

function epd_copyright_licensing_permission() {
  return array(
    'administer epd copyright and licensing' => array(
      'title' => t('Administer EPD Global Information'),
      'description' => t('Perform administration tasks for EPD global information.'),
    ),
  );
}
